--- 
javascripts: 
- base:
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - jrails
  - application
stylesheets: 
- base: 
  - jquery-ui-1.7.2.custom
  - screen
  - site
- print:
  - print
- ie:
  - ie


