development:
  access_key_id: AKIAIM5MDZOEI32BEIDA
  secret_access_key: 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
  bucket: grumpygrams-dev

test:
  access_key_id: AKIAIM5MDZOEI32BEIDA
  secret_access_key: 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
  bucket: grumpygrams-test

production:
  access_key_id: AKIAIM5MDZOEI32BEIDA
  secret_access_key: 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
  bucket: grumpygrams