# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

Gram.create!(:name => "The Grumpalupagus", :phrase => "Is someone doing a perfect impression of the Grumpa...", :image_file_name => "grumpalupagus_02.jpg", :image_content_type => "image/jpeg", :image_file_size => 55679, :position => 1, :recipient_phrase => "Grump Grump Grump!  A friend thinks your impression...", :facebook_tagline => "Grump! Grump! Grump!", :facebook_caption => "A friend thinks your impression of the Grumpalupagu...")
Gram.create!(:name => "Grumpzilla", :phrase => "Grumpzilla is on the rampage! Good thing you can't ...", :image_file_name => "grumpzilla_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 59281, :position => 2, :recipient_phrase => "Being Grumpzilla isn't going to change anything!  B...", :facebook_tagline => "Oh No! Here Comes Grumpzilla!", :facebook_caption => "Being Grumpzilla isn't going to change anything!  B...")
Gram.create!(:name => "The Grumpalope", :phrase => "Does someone need to chase the Grumpalope?", :image_file_name => "grumpalope_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 51184, :position => 3, :recipient_phrase => "Your friends have sent you on a wild Grumpalope cha...", :facebook_tagline => "Better Catch the Grumpalope!", :facebook_caption => "Your friends have sent you on a wild Grumpalope cha...")
Gram.create!(:name => "The Grump Truck", :phrase => "Beep, beep, beep!  Here comes the Grump Truck with ...", :image_file_name => "grumptruck_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 51882, :position => 4, :recipient_phrase => "Better back that Grump Truck up! Grumpiness is proh...", :facebook_tagline => "Beep! Beep! Beep!", :facebook_caption => "Better back that Grump Truck up! Grumpiness is proh...")
Gram.create!(:name => "Donald Grump", :phrase => "Did someone just get a Grump of the Month award fro...", :image_file_name => "donald_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 42897, :position => 5, :recipient_phrase => "Donald Grump likes your grumpy style. You'll be mov...", :facebook_tagline => "You've Won Grumployee Of the Month!", :facebook_caption => "Donald Grump likes your grumpy style. You'll be mov...")
Gram.create!(:name => "A Slice of Grumpkin Pie", :phrase => "Did someone just finish off the last slice of Grump...", :image_file_name => "pie_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 41648, :position => 6, :recipient_phrase => "How about some whipped cream to go with your slice ...", :facebook_tagline => "Grumpy And Got a Hankering For Something Sweet?", :facebook_caption => "How about a nice big Slice Of Grumpkin Pie?")
Gram.create!(:name => "Grumpus Maximus", :phrase => "Does someone think they are Emperor Grumpus Maximus...", :image_file_name => "maximus_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 56483, :position => 7, :recipient_phrase => "Someone had a bad day ruling their big strong empir...", :facebook_tagline => "All Hail Grumpus Maximus!", :facebook_caption => "Better throw your grumpiness to the lions!")
Gram.create!(:name => "The Grumble Bee", :phrase => "Is the Grumble Bee buzzing with grumpiness in the c...", :image_file_name => "bee_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 66074, :position => 8, :recipient_phrase => "Buzzing louder isn't going to change the fact that ...", :facebook_tagline => "Buzz! Buzz! Buzz!", :facebook_caption => "Buzzing louder isn't going to change the fact that ...")
Gram.create!(:name => "The Incredible Sulk", :phrase => "Has someone just turned into the Incredible Sulk?", :image_file_name => "sulk_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 45731, :position => 9, :recipient_phrase => "Time to get that grumpiness in check and stop being...", :facebook_tagline => "OH SIGH", :facebook_caption => "Time to get that grumpiness in check and stop being...")
Gram.create!(:name => "Grumpty Dumpty", :phrase => "Grumpty Dumpty at on a wall, Grumpy Dumpty had a gr...", :image_file_name => "grumpty_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 41445, :position => 10, :recipient_phrase => "All the King's Horses and All the King's men won't ...", :facebook_tagline => "Looks Like Someone Took Quite a Tumble!", :facebook_caption => "Too bad all the King's Horses and All the King's me...")
Gram.create!(:name => "Grumplestiltskin", :phrase => "Did your friend get swindled into some serious grum...", :image_file_name => "grumple_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 62410, :position => 11, :recipient_phrase => "Better give up your first born to Grumplestiltskin ...", :facebook_tagline => "Willing To Do Anything To Get Rid Of The Grumps?", :facebook_caption => "Maybe Grumplestiltskin can interest you in a trade?...")
Gram.create!(:name => "A Batch of Frownies", :phrase => "Mmm, mmm, mmm.  Smells like someone is baking up a ...", :image_file_name => "frownies_01.jpg", :image_content_type => "image/jpeg", :image_file_size => 55696, :position => 12, :recipient_phrase => "Don't leave that batch of Frownies in the oven for ...", :facebook_tagline => "Mmm, Mmm, Mmm!", :facebook_caption => "That Batch Of Frownies you're baking up sure smells...")